### ISSUE TITLE
Move script to SPM

### ISSUE THREAD

**Issue by feinstruktur** [qutheory/vapor-cli#24]
The main source file is getting quite big so I’ve taken a quick look into what it could look like broken up into separate files and built it with SPM on both OSX and Linux (DEVELOPMENT-SNAPSHOT-2016-05-09-a) here: https://github.com/qutheory/vapor-cli/tree/spm

The pros are:

- Better code organisation. There was already at least one case where duplicate functionality was implemented because the authors presumably didn’t see the pre-existing one (`getCommand(id:)`)
- Testability beyond just running the top level commands in Travis
- Fastest version deployed, don’t need to rely on people discovering and running `self compile` (plus we can get rid of that hack)
- We can use 3rd party libs that support OSX and Linux (like perhaps [Swiftline](https://github.com/oarrabi/Swiftline)) rather than re-implement everything ourselves just so we can stuff it into one file. (I checked that source libs get compiled into the resulting binary so we don’t have to deal with external frameworks or libs.)

Cons:

- Deployment is more complicated as we’d have to
  - build two variants, OSX and Linux - ideally automatically from Travis
  - switch on architecture on download or provide different d/l urls

**Comment by tannernelson** [comment]
I think it's necessary that we move to compiling it and separating out the source files. But this will take time to figure out how to do correctly so I think it makes sense as the next (0.6) release.

Maybe we could do something like the Swiftenv Travis CI gist where a script from a URL is read and evaluated to install. That way we can keep the one line install.

We could also consider adding it to Homebrew again, but I think that process is pretty annoying and still leaves us needing a method for Linux.

Before we approve this, I'd like to get @LoganWright's opinion.

**Comment by feinstruktur** [comment]
It looks like it should be easy to [save build artefacts to S3](https://docs.travis-ci.com/user/uploading-artifacts/). If we name them like so
```
$ echo vapor-$(git describe --always --tags --dirty)-$(uname)
vapor-0.4.0-Darwin
$ vapor docker enter
Starting bash in image qutheory/swift:DEVELOPMENT-SNAPSHOT-2016-05-09-a
root@eec02375ea8d:/vapor# echo vapor-$(git describe --always --tags --dirty)-$(uname)
vapor-0.4.0-Linux
```
we could get two versioned variant up to S3 and it’s then just a matter to resolve to those from the install URL, per platform.

If we don’t want to clutter up S3, this could be set up to only happen for builds from a, say, release branch. (For the tag name to appear as the version instead of a sha1 we’d need to make sure to push with a tag.)

**Comment by tannernelson** [comment]
We'd also need to detect the architecture of the machine, correct? Additionally, if they have Swift installed in different locations on the receiving computer, it will probably not be able to find the shared object files.

We could try this, but it would probably be more effective to have a script that compiles and installs the cli.

**Comment by feinstruktur** [comment]
I was hoping we could link with `-static-stdlib` but that doesn’t appear to be fully supported on Linux :/

We’re in a bit of pickle here.

Another thought: Self-compiling via `vapor-cli` seems to work ok, maybe the solution is to simply have a small swift bootstrap script that downloads and builds the SPM package. If we use swift to run this script we’ll ensure that swift is there and working, which should make the rest much easier.

Essentially, it could be

1) curl a bootstrap.swift
2) run it
3) this curls the full vapor-cli SPM
4) run `swift build` on it
5) install the result in a user defined location (e.g. a parameter from step 2)
6) clean up

**Comment by tannernelson** [comment]
Yeah a bootstrap is exactly what I was thinking. It could even be a shell script. That way we can give nicer warnings if Swift 3 isn't installed, instead of just a bunch of confusing compilation errors.

**Comment by feinstruktur** [comment]
I’ve added a script that should do this for both platforms to the `spm` branch: https://github.com/qutheory/vapor-cli/blob/spm/bootstrap.swift

**Comment by feinstruktur** [comment]
Could wrap this in a shell script to test swift availability but I’m not sure that’s worth it. You’ll end up being asked for a bash, csh, and fish version ;)
